server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      pattern: "%{X-Forwarded-For}i %T %D %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\""
      enabled: true
  compression:
    enabled: true
    mime-types: application/json
  port: 5000

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/bot?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
